version: '2'
services:
  redis:
    image: 'redis'
    restart: always
    networks:
      net:
        ipv4_address: 172.28.1.4
    environment:
      - REDIS_PASSWORD = redis
    ports:
      - '6379:6379'
  db:
    image: 'mariadb:latest'
    container_name: mariadb
    restart: always
    networks:
      net:
        ipv4_address: 172.28.1.3
    volumes:
      - './mysql/initdb/:/docker-entrypoint-initdb.d'
      - './mysql/data/:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      net:
        ipv4_address: 172.28.1.2
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    links:
      - 'db:db'
  server:
    build: ./server
    restart: always
    networks:
      net:
        ipv4_address: 172.28.1.1
    links:
      - 'db:db'
    ports:
      - '80:80'
    volumes:
      - './etc/nginx/:/etc/nginx/sites-enabled/'
      - './etc/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf'
      - './etc/supervisord.conf:/etc/supervisor/supervisord.conf'
      - './sites/:/var/www/html/'
      - './logs/:/var/log/nginx/'
      - './Ssl/:/root/Ssl/'
networks:
    net:
      ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16